namespace: gitlab

helmCharts:
  - name: gitlab
    releaseName: gitlab
    namespace: gitlab
    repo: https://charts.gitlab.io
    version: "7.0.4"
    valuesInline:
      global:
        https: true
        edition: ce
        hosts:
          domain: blahaj.sh
        hpa:
          apiVersion: "autoscaling/v2"
        pdb:
          apiVersion: "policy/v1"
        ingress:
          apiVersion: "networking.k8s.io/v1"
          class: ""
          enabled: true
          tls:
            secretName: gitlab-blahaj-cert
          configureCertmanager: false

      nginx-ingress:
        controller:
          extraArgs:
            workaround: issue 2487
        enabled: false

      upgradeCheck:
        enabled: false

      certmanager:
        install: false

      prometheus:
        install: false

      gitlab:
        gitaly:
          persistence:
            storageClass: longhorn

      postgresql:
        # # The chart is not up to date, the documentation is wrong :)
        # https://github.com/bitnami/charts/blob/09ba1564fed3df4f1d94518edcb58aab1f75c827/bitnami/postgresql/templates/statefulset.yaml
        master:
          persistence:
            storageClass: longhorn

      minio:
        persistence:
          storageClass: longhorn

      redis:
        master:
          persistence:
            storageClass: longhorn