apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitlab-proj
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: ArgoCD project for gitlab
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
