---
- name: Install Jellyfin
  ansible.builtin.import_playbook: diademiemi.jellyfin.install
  vars:
    target: local

- name: Install Intel Arc drivers
  ansible.builtin.import_playbook: diademiemi.jellyfin.intel_arc
  vars:
    target: local

...
