# This is a separate ArgoCD project since it would hang on this because of a bug and hang up other resources
# This is likely caused due to the GitLab chart using so many subcharts

namespace: gitlab

helmCharts:
  - name: gitlab
    releaseName: gitlab
    namespace: gitlab
    repo: https://charts.gitlab.io
    version: "7.0.4"
    valuesInline:
      global:
        https: true
        edition: ce
        hosts:
          domain: blahaj.sh
        hpa:
          apiVersion: "autoscaling/v2"
        pdb:
          apiVersion: "policy/v1"
        ingress:
          apiVersion: "networking.k8s.io/v1"
          class: "nginx"
          enabled: true
          tls:
            secretName: gitlab-blahaj-cert
          configureCertmanager: false

      nginx-ingress:
        controller:
          extraArgs:
            workaround: issue 2487
        enabled: false

      upgradeCheck:
        enabled: false

      certmanager:
        install: false

      prometheus:
        install: false

      gitlab-runner:
        runners:
          privileged: true  # For containers in containers
        checkInterval: 60
        concurrent: 5  # These devour CPU resources, I can't afford more
