---
- name: Deploy three VMs with Terraform
  hosts: localhost
  tags: terraform, vms
  tasks:
    - name: Prompt for confirmation
      ansible.builtin.pause:
        prompt: "This will remove all VMs and DELETE ALL DATA. Type 'yes' in all caps to confirm"
      register: confirmation
      run_once: true
      delegate_to: localhost

    - name: Fail if confirmation is not 'YES'
      ansible.builtin.fail:
        msg: "Confirmation not 'YES'"
      when:
        - confirmation.user_input != "YES"

    - name: Prompt for confirmation
      ansible.builtin.pause:
        prompt: "ARE YOU SURE? Type 'yes' in all caps to confirm"
      register: confirmation_2
      run_once: true
      delegate_to: localhost

    - name: Fail if confirmation is not 'YES'
      ansible.builtin.fail:
        msg: "Confirmation not 'YES'"
      when:
        - confirmation_2.user_input != "YES"

    - name: Delete Terraform project
      cloud.terraform.terraform:
        project_path: "{{ lookup('env', 'PWD') }}/terraform/vms"
        state: absent
        force_init: true
        variables_files:
          - "{{ lookup('env', 'PWD') }}/terraform/vms/env/vars.tfvars"
        variables:
          libvirt_uri: "{{ libvirt_connection_uri }}"

    - name: Remove tfstate file
      ansible.builtin.file:
        path: "{{ playbook_dir }}/../../terraform/{{ item }}"
        state: absent
      run_once: true
      delegate_to: localhost
      loop:
        - rancher/terraform.tfstate
        - rancher/terraform.tfstate.backup

...
