---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blahaj-sh-tls
  namespace: site-blahaj-sh
spec:
  secretName: blahaj-sh-tls
  commonName: blahaj.sh
  dnsNames:
    - blahaj.sh
  issuerRef:
    name: blahaj-issuer
    kind: ClusterIssuer
    group: cert-manager.io
...
