---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-blahaj-cert
  namespace: forgejo
spec:
  secretName: git-blahaj-cert
  commonName: "git.blahaj.sh"
  dnsNames:
    - "git.blahaj.sh"
  issuerRef:
    name: blahaj-issuer
    kind: ClusterIssuer
    group: cert-manager.io
...
