---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-blahaj-cert
  namespace: ingresses
spec:
  secretName: home-blahaj-cert
  commonName: home.blahaj.sh
  dnsNames:
    - blahaj.sh  # To work around https://letsencrypt.org/docs/duplicate-certificate-limit/
    - home.blahaj.sh
  issuerRef:
    name: blahaj-issuer
    kind: ClusterIssuer
    group: cert-manager.io
...
