namespace: nextcloud

generators:
  - ./kustomize-secret-generator.yaml

helmCharts:
  - name: nextcloud
    releaseName: nextcloud
    namespace: nextcloud
    repo: https://nextcloud.github.io/helm/
    version: "3.5.15"
    valuesInline:
      nextcloud:
        host: cloud.blahaj.sh
        existingSecret:
          enabled: true
          secretName: nextcloud-user
          usernameKey: username
          passwordKey: password
      cronjob:
        enabled: true

      persistence:
        enabled: true
        size: 50Gi
        nextcloudData:
          enabled: true

      ingress:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"  # Cloudflare handles this
          nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Cloudflare handles this
        tls:
          - hosts:
              - cloud.blahaj.sh
            secretName: cloud-blahaj-cert
      phpClientHttpsFix:
        enabled: true

      internalDatabase:
        enabled: false
      externalDatabase:
        enabled: true
        type: postgres
        host: postgres-service:5432
        database: nextcloud
        existingSecret:
          enabled: true
          secretName: nextcloud-postgresql
          usernameKey: username
          passwordKey: password

      postgresql:
        enabled: true
        primary:
          persistence:
            enabled: true
        auth:
          database: nextcloud
          username: nextcloud
          existingSecret: nextcloud-postgresql
          secretKeys:
            userPasswordKey: password
