apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-user
    namespace: nextcloud
stringData:
    username: ENC[AES256_GCM,data:ykcEnGru16WXXw==,iv:iY+sN9O7nr5Z+KfLoYMKCP+t/bMilPFaTO2YMKqHWpA=,tag:61LZ5d0LL0oOjEqR8F2GqQ==,type:str]
    password: ENC[AES256_GCM,data:lrUDwvuXCaZxIXaqVyXWHnxBttZJsqXiTYbKWqAymYc=,iv:077q/2LJ/K6DvMN3BXLeZpbjOGQQuy4y2diytIyAwpQ=,tag:vBcT4uAtOSVGd3/XKRnr8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mxkv9xclqht98ktax897v40rgcz89nfjt9e9m8260p36aqecaapqhxj2lr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQWZxajRkOFdYUStxTEJY
            Slh4aXRGdmc4RWYyK2UwMXozYW5HZTZOWXpJClI2aGtHakdZazRkUGxMZ3lRcVVL
            SnlFclh2cCt3Sm5LZVlGSU9lYXJRbHMKLS0tIEtoZHpzVGppMEZFQmtEZjRod28y
            NW8vNWQxaDZ1T0JRcG5SM2hpZmNzMk0KhUDxdq/HkpdLR7PImM5O9rXSkEe7GMcJ
            QHo3tK6MBKks2McL8d5JwWVq2qM7YLppbJHY7pNBFjM7oSpc/seGuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T11:21:09Z"
    mac: ENC[AES256_GCM,data:4QJo731HPBrn41s8V7ijrLwcHOG3Rs0/aEMpkUiDHU5DclqswzXM9en3cFpcn96IW9EaRLbL/e6UW+bj3EWwPiSwCVR+rklMcQLsH2YeLPCzQiZ+eKY1yNpvj2NRJBb5yODEfJi7sWzh/nBywiEalNPQP8vaHhph3Df827Q2R1I=,iv:P6DhAJuXs9VAPKIbjBSU0ZV2orzUlzKEMSrjmOgv6qg=,tag:QKZGL/frXl8lEYIvuJHdGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
