apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-postgresql
    namespace: nextcloud
data:
    username: ENC[AES256_GCM,data:9eAnl0vm0hYPlWYsUFzUGA==,iv:CSz98wZRBg3vFp6DptLYSmQ7lCuNx4OAUTzAdvp2EiY=,tag:BHsFmFwJA9o8m3Yv7uq96A==,type:str]
    password: ENC[AES256_GCM,data:ZORkOyYXsTJcnqSHVU6SiDSqFjzSZv8igAleEM7Sd1pM5vRliQunKzmHeQw=,iv:vmhcejmDiCKzx9ThdKaEj+tPqnKWYZzmXz23zsZWP1U=,tag:IepPcmOeUaMK9JFi01RCzw==,type:str]
    postgres-password: ENC[AES256_GCM,data:K0yoIuCxqggXIFl4RnMdyEeTZTap4isqWxyhM8axtxHJWAhR+Qx8fr/ZM/g=,iv:5H3GQ83kWF/Gyn+GirMRpwd96KIjdMDsoNzBEmNXukw=,tag:z9f5bc5+Ic99Fy+bH41mpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mxkv9xclqht98ktax897v40rgcz89nfjt9e9m8260p36aqecaapqhxj2lr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N0FyMjZ4VjhJaG50UWhK
            eU9iMVBQL3hlYzVMZnBzL295SWZNNFZOY1h3CkU4ZXNUTFFqVThUdlZGV1JjQUZU
            S3NwSkZISnR2eVQ1eHFNOW4xZFcxTlEKLS0tIDVuRDcrTXBTbjM0L0d0VjJQNC9z
            T0Z3Sm1wZktka1lUblhybDlJcWpIL2MKyKzskVsaoHgoX2cl/HJnjVPiOKElqhF9
            B/04tQFlR/w79hO1vU9VCnffgiCNsOuqSG7HqyYhSXMgRqcSt4v06g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-06T10:00:50Z"
    mac: ENC[AES256_GCM,data:85+enw5VK9RIDn0E+9DwRbluictlvSUaEVYkW8ZrcWZ8fDb/L31ffHGiZOYB1TX2VkXx3cKYKMWUWu7yWOo7UYUkDaQ06M75hUsIU+0nzBCl1A+DX08gY8Npqjs9RnxpBsy+PeYAD4bYuc/bIH0CIh5g62iFw4FSsjpMZhwZyTs=,iv:pcrxF9LyX1D5cHma6+1bH5VlIITw5+w9wRlQrC0nPJ0=,tag:mmnRUx+KCLZ1rV8HCQcTPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
