defaultNamespace: argocd

targetCustomizations:
- name: personal
  clusterSelector:
    matchLabels:
      identifier/name: personal
  kustomize:
    dir: overlays/personal

- name: public
  clusterSelector:
    matchLabels:
      identifier/name: public
  kustomize:
    dir: overlays/public
