---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: webring-proj
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: webring Setup
  destinations:
    - namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
...
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webring-app
  namespace: argocd
spec:
  project: webring-proj
  destination:
    namespace: 'webring'
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/queercoded-dev/argocd.git
    targetRevision: 'main'
    path: 'webring'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
...
