---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-ip
  namespace: ingresses
spec:
  ports:
  - name: http
    port: 8096
    protocol: TCP
  clusterIP: None
  type: ClusterIP
...
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin-ip
  namespace: ingresses
subsets:
- addresses:
  - ip: 192.168.100.130
  ports:
  - name: http
    port: 8096
    protocol: TCP
...
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-service
  namespace: ingresses
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"  # Cloudflare handles this
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Cloudflare handles this
spec:
  rules:
  - host: media.blahaj.sh
    http:
      paths:
      - backend:
          service:
            name: jellyfin-ip
            port:
              number: 8096
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - media.blahaj.sh
    secretName: media-blahaj-cert
...
